# Generated by Django 4.2.5 on 2023-10-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataencryptionrequest',
            name='work_status',
            field=models.TextField(choices=[('Введён', 'Introduced'), ('В работе', 'In Work'), ('Завершён', 'Finalised'), ('Отменён', 'Cancelled'), ('Удалён', 'Deleted')], default='Введён'),
        ),
    ]
