# Generated by Django 4.2.5 on 2023-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='data')),
                ('encription_status', models.CharField(choices=[('Зашифровано', 'Encrypted'), ('Оригинал', 'Original')])),
                ('status', models.CharField(choices=[('Удалён', 'Deleted'), ('Действует', 'In Effect')])),
            ],
        ),
    ]
