# Generated by Django 4.2.5 on 2023-09-28 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEncriptionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_status', models.IntegerField(choices=[('Введён', 'Introduced'), ('В работе', 'In Work'), ('Завершён', 'Finalised'), ('Отменён', 'Cancelled'), ('Удалён', 'Deleted')])),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 9, 28, 14, 48, 4, 917490))),
                ('formation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('is_moderator', models.BooleanField()),
            ],
        ),
    ]
