# Generated by Django 4.2.5 on 2023-09-28 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dataencriptionrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataencriptionrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 14, 48, 35, 387621)),
        ),
    ]
