# Generated by Django 4.2.5 on 2023-10-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dataitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='data_type',
            field=models.CharField(choices=[('Текстовый файл', 'Text File'), ('Код', 'Code'), ('Изображение', 'Image'), ('Директория', 'Directory')], default='Текстовый файл'),
        ),
    ]
