# Generated by Django 4.2.5 on 2023-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_dataitem_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='data_encription_request',
            field=models.ManyToManyField(to='app.dataencriptionrequest'),
        ),
    ]
