# Generated by Django 4.2.5 on 2023-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_dataitem_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='data_type',
            field=models.CharField(choices=[('Текстовый файл', 'Text File'), ('Код', 'Code'), ('Изображение', 'Image')], default='Текстовый файл'),
        ),
    ]
