# Generated by Django 4.2.5 on 2023-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_dataitem_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='status',
        ),
        migrations.AddField(
            model_name='dataitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
