# Generated by Django 4.2.5 on 2023-10-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dataencriptionrequest_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataencriptionrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
