# Generated by Django 4.2.5 on 2023-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_user_id_dataencriptionrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataencriptionrequest',
            name='work_status',
            field=models.IntegerField(choices=[('Введён', 'Introduced'), ('В работе', 'In Work'), ('Завершён', 'Finalised'), ('Отменён', 'Cancelled'), ('Удалён', 'Deleted')], default='Введён'),
        ),
    ]
