# Generated by Django 4.2.5 on 2023-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_dataencriptionrequest_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='data_encription_request',
        ),
        migrations.AddField(
            model_name='dataencriptionrequest',
            name='data_item',
            field=models.ManyToManyField(to='app.dataitem'),
        ),
    ]
