# Generated by Django 4.2.5 on 2023-11-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Имя пользователя')),
                ('role', models.IntegerField(blank=True, choices=[(1, 'User'), (2, 'Moderator'), (3, 'Admin')], default=1, verbose_name='Роль пользователя')),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, upload_to='data')),
                ('is_encrypted', models.IntegerField(choices=[(1, 'Encrypted'), (2, 'Original')], default=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_type', models.IntegerField(choices=[(1, 'Text File'), (2, 'Code'), (3, 'Image')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DataEncryptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.TextField(choices=[('Черновик', 'Draft'), ('Сформирован', 'Formed'), ('Завершён', 'Finalised'), ('Отменён', 'Cancelled'), ('Удалён', 'Deleted')], default='Черновик')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('formation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.IntegerField(default=0)),
                ('data_item', models.ManyToManyField(to='encryption.dataitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
