# Generated by Django 4.2.5 on 2023-12-04 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, upload_to='data')),
                ('is_encrypted', models.IntegerField(choices=[(1, 'Encrypted'), (2, 'Original')], default=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_type', models.IntegerField(choices=[(1, 'Text File'), (2, 'Code'), (3, 'Image')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DataEncryptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.TextField(choices=[('Черновик', 'Draft'), ('Сформирован', 'Formed'), ('Завершён', 'Finalised'), ('Отменён', 'Cancelled'), ('Удалён', 'Deleted')], default='Черновик')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('formation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.IntegerField(choices=[(0, 'Encrypt'), (1, 'Decrypt')], default=0)),
                ('data_item', models.ManyToManyField(to='encryption.dataitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
