# Generated by Django 4.2.5 on 2023-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('role', models.IntegerField(choices=[(1, 'User'), (2, 'Moderator'), (3, 'Admin')], default=1, verbose_name='Кем является пользователь?')),
            ],
        ),
    ]
