# Generated by Django 4.2.5 on 2023-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
