# Generated by Django 4.2.5 on 2023-11-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0003_encryptionuser_groups_encryptionuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptionpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='encryptionpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='EncryptionGroup',
        ),
        migrations.DeleteModel(
            name='EncryptionPermission',
        ),
    ]
