# Generated by Django 4.2.5 on 2023-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0005_alter_encryptionuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
