# Generated by Django 4.2.5 on 2023-11-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0006_alter_encryptionuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataencryptionrequest',
            name='action',
            field=models.IntegerField(choices=[(0, 'Encrypt'), (1, 'Decrypt')], default=0),
        ),
    ]
